### ISSUE TITLE
Golang naming conventions

### ISSUE THREAD

**Issue by JustDaile** [BEOpenSourceCollabs/EventManagementCore#17]
All files using the typical js type naming convention of `login.success.go` should be updated as such `login_success.go`

**Comment by vivekup3424** [comment]
Hey, I just saw your issue, and I have made the changes and will soon will send the pull-request, please tell me if there is anything more I can do there. Maybe I should create a new branch for the changes?

**Comment by JustDaile** [comment]
Sure, go for it, you can join the discord: https://discord.gg/t7qysRxj
